# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Create an AppImage release for every commit

on:
  push

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::$(grep -Po 'version="\K((\d|\.)+)' setup.py)

      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          APPIMAGE_BUILDER_VERSION: ${{ steps.get_version.outputs.VERSION }}
        with:
          recipe: AppImageBuilder.yml
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2.1.4
        with:
          name: artifacts
          path: './appimage-builder*.AppImage*'